Repository driggl/linklog, pull requests merged in 2020-05, with the labels that each got.

#7 Fake data seeders
  .overcommit.yml
  api/Gemfile
  api/Gemfile.lock
  api/db/seeds.rb
  api/lib/seeders/articles_seed.rb
  api/lib/seeders/users_seed.rb
  api/spec/lib/seeders/articles_seed_spec.rb
  api/spec/lib/seeders/users_seed_spec.rb
Labels: API, enhancement

#22 Unit tests configuration
  ui/test/Logo.spec.js
  ui/test/specs/layouts/default.spec.js
  ui/test/specs/pages/index.spec.js
  ui/test/utils.js
Labels: WIP

#23 Database setup for CI/CD
  .github/workflows/ruby.yml
  README.md
Labels: API, WIP
